suggestions_map = {
        "hello": ["Hello!", "Hey!", "How are you?", "Hi there!", "Hey, what's up?"],
        "hi": ["Hi there!", "Hey!", "What's up?", "Hello!", "Good to see you!"],
        "how are you": ["I'm doing great!", "I'm fine, how about you?", "All good!", "Not bad!", "Just taking it easy!"],
        "what's up": ["Not much, you?", "Just chilling!", "All good here!", "Just working on something!", "Nothing much, how about you?"],
        "good morning": ["Good morning!", "Hope you have a great day!", "Morning!", "Rise and shine!", "Wishing you a great morning!"],
        "good night": ["Good night!", "Sweet dreams!", "Sleep well!", "Have a restful night!", "See you tomorrow!"],
        "bye": ["Goodbye!", "See you later!", "Take care!", "Catch you later!", "Until next time!"],
        "thank you": ["You're welcome!", "No problem!", "Anytime!", "Glad I could help!", "Much appreciated!"],
        "sorry": ["No worries!", "It's okay!", "Don't worry about it!", "I understand!", "Happens to the best of us!"],
        "yes": ["Great!", "Awesome!", "Okay!", "Sounds good!", "Absolutely!"],
        "no": ["Alright!", "No problem!", "Maybe next time!", "I understand!", "Fair enough!"],
        "help": ["How can I assist you?", "What do you need help with?", "I'm here to help!", "Need some guidance?", "Let me know what you need!"],
        "how's your day": ["Pretty good!", "Busy but good!", "Can't complain!", "Just another day!", "Going well so far!"],
        "what are you doing": ["Just working on something!", "Not much, you?", "Taking a break!", "Keeping busy!", "Just relaxing!"],
        "tell me more": ["Sure! What do you want to know?", "I'd love to explain further!", "Let me elaborate!", "Here are the details!", "Happy to share more!"],
        "let's do it": ["Sounds good!", "I'm in!", "Let's go!", "Let's make it happen!", "I'm ready!"],
        "maybe": ["That's fair!", "We can think about it more!", "Let's see how it goes!", "Good point!", "We’ll decide later!"],
        "why not": ["Exactly!", "Good point!", "Let's give it a try!", "I like that idea!", "No reason not to!"],
        "interesting": ["Yeah, right?", "Tell me more!", "I agree!", "That's a new perspective!", "That's worth thinking about!"],
        "really?": ["Yes, really!", "Absolutely!", "Why do you ask?", "It's true!", "Believe it or not, yes!"],
        "i don't know": ["That's okay!", "No worries, take your time!", "Want to figure it out together?", "Let's think about it!", "We'll find out!"],
        "let's go": ["Yeah, let's do it!", "I'm ready!", "Let's get started!", "Let's move!", "Time to roll!"],
        "what do you mean": ["I mean exactly that!", "Let me clarify!", "Could you specify what part?", "I can explain further!", "Here’s what I meant!"],
        "wait a minute": ["Sure, take your time!", "I'll wait!", "No rush!", "Go ahead!", "Take your time!"],
        "wow": ["I know, right?", "Amazing, isn't it?", "That's incredible!", "Unbelievable!", "Mind-blowing!"],
        "haha": ["Glad you found it funny!", "LOL!", "That was a good one!", "Haha, true!", "Nice one!"],
        "seriously": ["Yeah, totally!", "I mean it!", "No joke!", "100%!", "For real!"],
        "hmm": ["Thinking about it?", "Interesting thought!", "Deep in thought?", "Let me know what you decide!", "Sounds like you're contemplating!"],
        "let me know": ["Of course!", "I'll keep you posted!", "Sure thing!", "I'll update you!", "Will do!"],
        "congratulations": ["Congrats!", "Well done!", "Good job!", "I'm so happy for you!", "That's fantastic!"],
        "happy birthday": ["Happy Birthday!", "Many happy returns!", "Have a great day!", "Wishing you all the best!", "Enjoy your special day!"],
        "good luck": ["Best of luck!", "You got this!", "All the best!", "Fingers crossed!", "Wishing you success!"],
        "take care": ["Stay safe!", "Look after yourself!", "Be careful!", "Take it easy!", "See you soon!"],
        "i love you": ["I love you too!", "You're the best!", "So sweet!", "Love you more!", "You mean the world to me!"],
        "miss you": ["Miss you too!", "Can't wait to see you!", "Thinking of you!", "Hope to see you soon!", "Wish you were here!"],
        "good job": ["Well done!", "Great work!", "Keep it up!", "Nice job!", "Proud of you!"],
        "good evening": ["Good evening!", "Hope you had a great day!", "Evening!", "How was your day?", "Wishing you a pleasant evening!"],
        "good afternoon": ["Good afternoon!", "Hope your day is going well!", "Afternoon!", "How's your day going?", "Wishing you a great afternoon!"],
        "goodbye": ["Goodbye!", "See you later!", "Take care!", "Catch you later!", "Until next time!"],
        "see you": ["See you soon!", "Catch you later!", "Until next time!", "Take care!", "Goodbye!"],
        "nice to meet you": ["Nice to meet you too!", "Pleasure meeting you!", "Great to meet you!", "Lovely to meet you!", "Nice meeting you!"],
        "how's it going": ["It's going well!", "All good, you?", "Pretty good, how about you?", "Can't complain!", "Going great!"],
        "what's new": ["Not much, you?", "Just the usual!", "Same old, same old!", "Nothing new here!", "What's new with you?"],
        "long time no see": ["Yeah, it's been a while!", "Good to see you again!", "It's been too long!", "How have you been?", "Missed you!"],
        "how can i help you": ["I need some assistance with something.", "Can you help me with this?", "I have a question.", "I need your help.", "Can you assist me?"],
        "what's your name": ["I'm GitHub Copilot!", "You can call me Copilot.", "I'm your assistant.", "I'm here to help you.", "I'm an AI assistant."],
        "how can i help you": ["I need some assistance with something.", "Can you help me with this?", "I have a question.", "I need your help.", "Can you assist me?"],
        "what's your name": ["I'm GitHub Copilot!", "You can call me Copilot.", "I'm your assistant.", "I'm here to help you.", "I'm an AI assistant."],
        "how are you": ["I'm good, thanks!", "Doing well, you?", "Pretty good, how about you?", "Can't complain!", "All good here!"],
        "what do you think": ["I think it's great!", "Sounds good to me!", "I like it!", "Looks good!", "I agree!"],
        "do you agree": ["Yes, I agree!", "Absolutely!", "For sure!", "Definitely!", "I think so too!"],
        "i'm bored": ["Let's do something fun!", "How about a game?", "Want to chat?", "Let's find something interesting to do!", "Any hobbies you enjoy?"],
        "i'm tired": ["Take a rest!", "You should relax.", "Get some sleep.", "Take it easy.", "Rest up!"],
        "i'm hungry": ["Grab a snack!", "Time to eat!", "What's for dinner?", "Let's find some food.", "Feeling like a meal?"],
        "i'm excited": ["That's awesome!", "Great to hear!", "So exciting!", "Can't wait!", "Tell me more!"],
        "i'm sad": ["I'm here for you.", "Want to talk about it?", "I'm sorry to hear that.", "Anything I can do?", "Sending positive vibes!"],
        "i'm confused": ["Can you clarify?", "I'm not sure I understand.", "Could you explain that?", "I'm a bit lost.", "Can you help me understand?"],
        "i'm happy": ["That's great!", "Awesome!", "Glad to hear!", "Fantastic!", "That's wonderful!"],
        "i'm worried": ["What's on your mind?", "Want to talk about it?", "I'm here for you.", "Anything I can do?", "Don't worry, it'll be okay."],
        "i'm stressed": ["Take a deep breath.", "Try to relax.", "It'll be okay.", "Take it one step at a time.", "I'm here for you."],
        "i'm annoyed": ["What's bothering you?", "Want to talk about it?", "I'm here to listen.", "Anything I can do?", "Let's figure this out."],
        "i'm curious": ["What are you curious about?", "Let's explore that!", "Tell me more!", "I'm interested too!", "Let's find out!"],
        "i'm frustrated": ["I'm sorry to hear that.", "Want to talk about it?", "I'm here for you.", "Anything I can do?", "Let's work through it together."],
        "i'm grateful": ["That's wonderful!", "Glad to hear!", "That's great!", "I'm happy for you!", "That's awesome!"],
        "i'm surprised": ["Wow, really?", "That's surprising!", "Didn't expect that!", "That's interesting!", "Tell me more!"],
        "i'm impressed": ["That's impressive!", "Well done!", "Great job!", "I'm amazed!", "That's fantastic!"],
        "i'm disappointed": ["I'm sorry to hear that.", "That's unfortunate.", "Want to talk about it?", "I'm here for you.", "Anything I can do?"],
        "i'm hopeful": ["That's great!", "Fingers crossed!", "Hope it works out!", "Wishing you the best!", "Stay positive!"],
        "i'm nervous": ["It's okay to feel nervous.", "Take a deep breath.", "You'll do great!", "I'm here for you.", "Everything will be fine."],
        "i'm scared": ["It's okay to be scared.", "I'm here for you.", "You can do this.", "Take a deep breath.", "Everything will be okay."],
        "i'm proud": ["That's fantastic!", "Well done!", "Great job!", "I'm proud of you!", "Keep up the good work!"],
        "i'm jealous": ["It's natural to feel that way.", "Want to talk about it?", "I'm here for you.", "Let's work through it together.", "It's okay to feel jealous."],
        "i'm lonely": ["I'm here for you.", "Want to chat?", "Let's talk.", "You're not alone.", "I'm here to listen."],
        "i'm overwhelmed": ["Take a deep breath.", "One step at a time.", "You can do this.", "I'm here for you.", "Let's work through it together."],
        "i'm relaxed": ["That's great!", "Glad to hear!", "Enjoy the moment.", "That's wonderful!", "Keep it up!"],
        "i'm motivated": ["That's awesome!", "Keep going!", "You got this!", "Stay focused!", "Great to hear!"],
        "i'm determined": ["That's fantastic!", "Keep it up!", "You can do this!", "Stay strong!", "Great to hear!"],
        "i'm amused": ["That's funny!", "Glad to hear!", "That's amusing!", "Tell me more!", "That's interesting!"],
        "i'm content": ["That's great!", "Glad to hear!", "That's wonderful!", "Keep it up!", "Fantastic!"],
        "i'm relaxed": ["That's great!", "Glad to hear!", "Enjoy the moment.", "That's wonderful!", "Keep it up!"],
        "how's everything": ["All good!", "Everything's going well!", "Can't complain!", "Things are going smoothly.", "Everything's great!"],
        "have you heard": ["No, what happened?", "What’s the news?", "Tell me more!", "I haven't, what is it?", "What's going on?"],
        "what's your opinion": ["I think it's a good idea.", "Here's what I think...", "In my opinion, it's worth considering.", "I believe it could work.", "I think it's a great idea!"],
        "that's funny": ["Haha, right?", "Good one!", "I thought you'd like that!", "LOL, true!", "Haha, you got me there!"],
        "tell me about it": ["Sure, where should I start?", "Let me explain!", "Happy to share!", "Here's what I know.", "I’d love to tell you!"],
        "no worries": ["All good!", "It's fine!", "No problem at all!", "Don't worry about it!", "No need to apologize!"],
        "you're welcome": ["Anytime!", "Glad I could help!", "It’s my pleasure!", "You're very welcome!", "Happy to help!"],
        "good to know": ["Glad to hear that!", "Thanks for letting me know!", "That’s useful!", "Good info!", "Thanks for sharing!"],
        "take it easy": ["You too!", "Relax and enjoy!", "Take care of yourself!", "Don't stress too much!", "Stay calm and relaxed!"],
        "what happened": ["Not much, what's up?", "Something interesting, tell me!", "What do you mean?", "What’s going on?", "Can you clarify?"],
        "never mind": ["Alright, no problem!", "Got it, forget about it!", "No worries, it's fine.", "Okay, if you say so.", "Sure, let's move on!"],
        "let's chat": ["Sure, what’s on your mind?", "I'd love to!", "Let's talk about it.", "What do you want to chat about?", "I'm all ears!"],
        "what's the deal": ["Not much, what about you?", "Same as usual.", "What's going on with you?", "What's happening?", "Tell me more!"],
        "you got this": ["Thanks! I’ll do my best!", "I hope so!", "I’m feeling confident!", "I’m going to give it my all!", "Thanks for the support!"],
        "take your time": ["Thanks, I will!", "No rush!", "I'll be careful!", "Appreciate it!", "I'll take my time!"],
        "that's true": ["Glad we agree!", "Exactly!", "I think so too!", "Yeah, you're right!", "That's a good point!"],
        "I can't wait": ["I’m excited too!", "Same here!", "It’s going to be awesome!", "Looking forward to it!", "I’m thrilled!"],
        "count me in": ["Awesome, you're in!", "Great to hear!", "Let's do it!", "You're on the team!", "Glad you're joining!"],
        "are you sure": ["Absolutely sure!", "Yes, I’m positive.", "I’m certain about it!", "Without a doubt!", "I'm completely sure!"],
        "that's crazy": ["I know, right?", "Unbelievable!", "So wild!", "Can you believe it?", "That’s mind-blowing!"],
        "we'll see": ["Let's wait and see.", "Time will tell.", "We’ll figure it out.", "It’s up in the air.", "Let's see what happens."],
        "I hope so": ["Me too!", "Fingers crossed!", "Let’s hope for the best!", "I really hope it works out.", "I’m hoping for that too!"],
        "I don't mind": ["That's good to hear!", "No problem at all!", "Whatever works for you!", "It's all good!", "Sounds fine to me!"],
        "I agree": ["I'm with you on that!", "Definitely!", "You’re right!", "Totally agree!", "I feel the same way!"],
        "it's all good": ["No problem!", "Everything’s fine!", "All is well!", "Everything’s alright!", "Don’t worry about it!"],
        "it's up to you": ["I’ll leave it to you.", "Your call!", "I trust your decision!", "It's your choice!", "Whatever you decide!"],
        "I understand": ["Glad to hear that!", "Got it!", "Makes sense!", "I see where you're coming from.", "I get it!"],
        "that's a good idea": ["I think so too!", "Great suggestion!", "I like that idea!", "Sounds like a plan!", "Great thinking!"],
        "sounds fun": ["Yeah, I’m in!", "That does sound fun!", "I’m up for that!", "Count me in!", "Let’s make it happen!"],
        "I didn't mean to": ["It's okay!", "No worries at all!", "I understand!", "No harm done!", "Don't worry about it!"],
        "sounds like a plan": ["I’m in!", "Let’s do it!", "That works for me!", "Great plan!", "Let's get started!"],
        }